### ISSUE TITLE
stm32f1 update?

### ISSUE THREAD

**Issue by mgiaco** [MaJerle/Embedded_Libs#2]
Hi,

Do you plan any update for stm32f1?

thx

**Comment by MaJerle** [comment]
Not unfortunately.

**Comment by mgiaco** [comment]
Okay but do you think the new freertos works for the f1 without any problems?

**Comment by MaJerle** [comment]
It worked well on F4, G0 and L4, so I assume F1 is ok aswell. Portable part shall not be changed.
On the other hand, you may still use previous version, just check commit number and make submodule from that commit (if you are unsure).

**Comment by mgiaco** [comment]
Okay I will try because I would like to use the latest cmsis os v2. And I would like to use the lates F1 HAL 1.7.0 
many thanks for your help
