### ISSUE TITLE
fatal: No url found for submodule path 'third_party/Embedded_Libs' in .gitmodules

### ISSUE THREAD

**Issue by elektronchika** [MaJerle/Embedded_Libs#3]
Hi,

when I execute git submodule update --init --recursive I get the following error: fatal: No url found for submodule path 'third_party/Embedded_Libs' in .gitmodules

Could it be that the link in .gitmodules is broken?

Thanks!

**Comment by MaJerle** [comment]
This repo has no submodules. Which repository are you referring to please?

**Comment by elektronchika** [comment]
Please excuse me, I should have opened the issue in the EasyGUI repo...
