### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by drorgl** [MaJerle/Embedded_Libs#4]
Hi,

The licensing for the repo is a contradictory.

The header of [tm_stm32_buffer.h](https://github.com/MaJerle/embedded-libs/blob/master/tm_stm32_buffer.h) is GPL while the project [LICENSE](https://github.com/MaJerle/embedded-libs/blob/master/LICENSE) is MIT.

Can you please update the project to reflect your choice?

**Comment by MaJerle** [comment]
Hello Drorgl,

you are right, it is a mistake since licensing was changed later.

If you are looking for ring buffer, please have a look at this library instead: https://github.com/MaJerle/lwrb
Much more comprehensive and platform independent + has necessary docs available.
